### ISSUE TITLE
Cheat followers

### ISSUE THREAD

**Issue by serhiiboreiko** [ixrock/XTranslate#11]
Your extension added script that cheat followers on Instagram and YouTube. I wrote a complaint to your extension to Google Support!

**Comment by ixrock** [comment]
How exactly it cheat followers?

Sure, you can write whatever you want, but **extension doesn't do anything without user's granted allowance** (when trial period is over the app ask user to buy the extension or continue using by allowing injecting ads at visiting pages, then and only then something might happen what i for sure don't know, because it's ads partner script might do something fishy).

Write me what exactly wrong and I can ask explanations from ads-partner feedback.

**Comment by serhiiboreiko** [comment]
When i go to Instagram or YouTube from browser. I see that my count of "following" increases. This happens because of your extension. If i open inspector and open sources i can see scripts from your extension. One script contains array of people nicknames which then shows up in my "following". If i turn off your extension this is gone. I would not write anything if it was advertising. But my account manipulation is bad. If you do not like this, please, remove this and let me know.

**Comment by ixrock** [comment]
Can you reproduce it once again and create screencast video and/or provide more information from devtools panel? loaded scripts, urls, script contents?

**Comment by serhiiboreiko** [comment]
A couple of hours.

**Comment by ixrock** [comment]
I couldn't get any meaningful response from ads partner, so i decided to add instagram in white list, so starting from v.2.2.7 even if ads allowed in general the script won't be injected there.
