### ISSUE TITLE
Translation of "use_chrome_tts" 

### ISSUE THREAD

**Issue by Etamuk** [ixrock/XTranslate#19]
Hello,

I tried to translate the strings for "use_chrome_tts" into german but can not get the right meaning of it. 
Does it mean "use the tts engine of the system" (does any computer system offer this?) or does it mean "use the tts engine from chrome browser"? 
I am using Vivaldi as browser and when I activate this option in Xtranslate I don't get tts-output anymore.

Could you please tell me the meaning of it?
Thank you and best regards from germany

**Comment by ixrock** [comment]
Hi! It means to force use https://developer.chrome.com/apps/tts chrome api instead of supported (if any) tts engine from translation vendors (google, yandex, etc.)
Since yandex & bing has very poor support I removed them from the code and was hoping this chrome.tts api would be enough.
But the problem seems that Vivaldi and possibly other browsers based on chrome-engine won't support this api. 
Have to think more what can be done better in this case..

**Comment by ixrock** [comment]
For now just keep it turned off and if you need text-to-speech option you can get it from translation with Google.
