### ISSUE TITLE
429: Data loading failed(Service unavailable.)

### ISSUE THREAD

**Issue by anigkus** [ixrock/XTranslate#49]
### System
``` macOS Monterey v12.2.1 ```

### Google Chrome
```
Version 100.0.4896.88 (Official Build) (x86_64)
```

###Url
https://github.com/ixrock/XTranslate

### XTranslate Version
```2.64.0```

#### Detail  please look  image
<img width="1423" alt="1" src="https://user-images.githubusercontent.com/88264073/164583117-ac1c7856-4859-4f46-bf89-2b1a02e11240.png">

**Comment by ixrock** [comment]
If this error happens time to time try to increase this timeout:

(it prevents to tackle google apis too often while typing text slowly, so google in that case less aggressive in "catching" suspicious traffic, otherwise it might ban for a while as described in the issue).

<img width="598" alt="Screenshot 2022-05-13 at 14 55 01" src="https://user-images.githubusercontent.com/6377066/168278501-2d7e3136-6e96-4e7d-ba46-add854e58646.png">

Otherwise api-server probably not available/flaky/etc. in your country (url currently not editable in app and equals to https://translate.googleapis.com).
