### ISSUE TITLE
Is there a way to select a dialect?

### ISSUE THREAD

**Issue by vadimk1337** [ixrock/XTranslate#50]
The fact is that Google determines the dialect of the English language depending on the ip address  https://translate.google.com/.  For me it's British, for the US it's a US dialect. Google allows you to select a dialect through another link 
1)https://translate.google.as/ - Us  
2) https://translate.google.co.uk/ - Brit. 
 Is it possible to somehow modify the code so that you can change the dialect in the settings? 

- auto
- us
- brit

 I just want to listen to the US dialect.

**Comment by ixrock** [comment]
Currently it's not possible in the app. 

_Here is what is used:_
`https://translate.google.com/translate?tl=${lang}&u=${pageUrl}`
Most probably it's missing some extra query, e.g. `?param=value` to specify desired desired dialect version.

Otherwise please provide all supported dialects/hosts list mapping or where to find docs about it (this will speed up issue resolving).
